quiet: false
disable-version-string: true
with-expecter: true
all: true
mockname: "{{.InterfaceName}}"
filename: "{{.MockName}}.go"
outpkg: "mocks"
packages:
  github.com/intility/cwc/internal:
    config:
      dir: internal/mocks