// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// FileReader is an autogenerated mock type for the FileReader type
type FileReader struct {
	mock.Mock
}

type FileReader_Expecter struct {
	mock *mock.Mock
}

func (_m *FileReader) EXPECT() *FileReader_Expecter {
	return &FileReader_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: path
func (_m *FileReader) Execute(path string) ([]byte, error) {
	ret := _m.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return rf(path)
	}
	if rf, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = rf(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(path)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FileReader_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type FileReader_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - path string
func (_e *FileReader_Expecter) Execute(path interface{}) *FileReader_Execute_Call {
	return &FileReader_Execute_Call{Call: _e.mock.On("Execute", path)}
}

func (_c *FileReader_Execute_Call) Run(run func(path string)) *FileReader_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *FileReader_Execute_Call) Return(_a0 []byte, _a1 error) *FileReader_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *FileReader_Execute_Call) RunAndReturn(run func(string) ([]byte, error)) *FileReader_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewFileReader creates a new instance of FileReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFileReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *FileReader {
	mock := &FileReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
