// Code generated by mockery. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Marshaller is an autogenerated mock type for the Marshaller type
type Marshaller struct {
	mock.Mock
}

type Marshaller_Expecter struct {
	mock *mock.Mock
}

func (_m *Marshaller) EXPECT() *Marshaller_Expecter {
	return &Marshaller_Expecter{mock: &_m.Mock}
}

// Marshal provides a mock function with given fields: in
func (_m *Marshaller) Marshal(in interface{}) ([]byte, error) {
	ret := _m.Called(in)

	if len(ret) == 0 {
		panic("no return value specified for Marshal")
	}

	var r0 []byte
	var r1 error
	if rf, ok := ret.Get(0).(func(interface{}) ([]byte, error)); ok {
		return rf(in)
	}
	if rf, ok := ret.Get(0).(func(interface{}) []byte); ok {
		r0 = rf(in)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(interface{}) error); ok {
		r1 = rf(in)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Marshaller_Marshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Marshal'
type Marshaller_Marshal_Call struct {
	*mock.Call
}

// Marshal is a helper method to define mock.On call
//   - in interface{}
func (_e *Marshaller_Expecter) Marshal(in interface{}) *Marshaller_Marshal_Call {
	return &Marshaller_Marshal_Call{Call: _e.mock.On("Marshal", in)}
}

func (_c *Marshaller_Marshal_Call) Run(run func(in interface{})) *Marshaller_Marshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *Marshaller_Marshal_Call) Return(_a0 []byte, _a1 error) *Marshaller_Marshal_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *Marshaller_Marshal_Call) RunAndReturn(run func(interface{}) ([]byte, error)) *Marshaller_Marshal_Call {
	_c.Call.Return(run)
	return _c
}

// Unmarshal provides a mock function with given fields: in, out
func (_m *Marshaller) Unmarshal(in []byte, out interface{}) error {
	ret := _m.Called(in, out)

	if len(ret) == 0 {
		panic("no return value specified for Unmarshal")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte, interface{}) error); ok {
		r0 = rf(in, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Marshaller_Unmarshal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unmarshal'
type Marshaller_Unmarshal_Call struct {
	*mock.Call
}

// Unmarshal is a helper method to define mock.On call
//   - in []byte
//   - out interface{}
func (_e *Marshaller_Expecter) Unmarshal(in interface{}, out interface{}) *Marshaller_Unmarshal_Call {
	return &Marshaller_Unmarshal_Call{Call: _e.mock.On("Unmarshal", in, out)}
}

func (_c *Marshaller_Unmarshal_Call) Run(run func(in []byte, out interface{})) *Marshaller_Unmarshal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte), args[1].(interface{}))
	})
	return _c
}

func (_c *Marshaller_Unmarshal_Call) Return(_a0 error) *Marshaller_Unmarshal_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Marshaller_Unmarshal_Call) RunAndReturn(run func([]byte, interface{}) error) *Marshaller_Unmarshal_Call {
	_c.Call.Return(run)
	return _c
}

// NewMarshaller creates a new instance of Marshaller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMarshaller(t interface {
	mock.TestingT
	Cleanup(func())
}) *Marshaller {
	mock := &Marshaller{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
