// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	config "github.com/intility/cwc/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// optFunc is an autogenerated mock type for the optFunc type
type optFunc struct {
	mock.Mock
}

type optFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *optFunc) EXPECT() *optFunc_Expecter {
	return &optFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *optFunc) Execute(_a0 *config.DefaultProviderOptions) {
	_m.Called(_a0)
}

// optFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type optFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 *config.DefaultProviderOptions
func (_e *optFunc_Expecter) Execute(_a0 interface{}) *optFunc_Execute_Call {
	return &optFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *optFunc_Execute_Call) Run(run func(_a0 *config.DefaultProviderOptions)) *optFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*config.DefaultProviderOptions))
	})
	return _c
}

func (_c *optFunc_Execute_Call) Return() *optFunc_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *optFunc_Execute_Call) RunAndReturn(run func(*config.DefaultProviderOptions)) *optFunc_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// newOptFunc creates a new instance of optFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newOptFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *optFunc {
	mock := &optFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
