// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	user "os/user"

	mock "github.com/stretchr/testify/mock"
)

// UsernameRetriever is an autogenerated mock type for the UsernameRetriever type
type UsernameRetriever struct {
	mock.Mock
}

type UsernameRetriever_Expecter struct {
	mock *mock.Mock
}

func (_m *UsernameRetriever) EXPECT() *UsernameRetriever_Expecter {
	return &UsernameRetriever_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields:
func (_m *UsernameRetriever) Execute() (*user.User, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *user.User
	var r1 error
	if rf, ok := ret.Get(0).(func() (*user.User, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *user.User); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*user.User)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UsernameRetriever_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type UsernameRetriever_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
func (_e *UsernameRetriever_Expecter) Execute() *UsernameRetriever_Execute_Call {
	return &UsernameRetriever_Execute_Call{Call: _e.mock.On("Execute")}
}

func (_c *UsernameRetriever_Execute_Call) Run(run func()) *UsernameRetriever_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *UsernameRetriever_Execute_Call) Return(_a0 *user.User, _a1 error) *UsernameRetriever_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *UsernameRetriever_Execute_Call) RunAndReturn(run func() (*user.User, error)) *UsernameRetriever_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// NewUsernameRetriever creates a new instance of UsernameRetriever. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUsernameRetriever(t interface {
	mock.TestingT
	Cleanup(func())
}) *UsernameRetriever {
	mock := &UsernameRetriever{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
